name: Build And Deploy
run-name: Deploy puntuaciones.jaimeelingeniero.es to AWS S3

on:
  workflow_dispatch: # allow manual trigger
  push:
    tags: ["[1-9].[0-9][0-9]?.[0-9][0-9]?"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: "@jaimemartinmartin15"
      - name: Install
        run: npm ci --no-audit --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Generate icons
        run: npm run icons
      - name: Build
        run: npm run build
      - name: Unit test
        run: npm run test:ci
      # TODO fix this stage: Error: Failed to launch the browser process! No usable sandbox! Update your kernel or see 
      # TODO https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox.
      # TODO If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
      # - name: E2e test
      #   run: npm run test:e2e
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-south-2
      - name: Deploy
        run: |
          aws --version
          aws s3 sync ./dist/puntuaciones/browser \
                      s3://puntuaciones.jaimeelingeniero.es \
                      --delete \
                      --exclude 3rdpartylicenses.txt
          aws s3 cp ./dist/puntuaciones/3rdpartylicenses.txt s3://puntuaciones.jaimeelingeniero.es
